export const ads = [
  {
    id:1,
    image: new URL("../../public/products/cap.png", import.meta.url).href,
    location: "г. Ташкент",
    descraption: "Кепки Corneliani Diamond for him edition.",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "2 599 000",
    miniImage: new URL ("../../public/miniProducts/Image (1).png", import.meta.url).href,
    miniImage2: new URL ("../../public/miniProducts/Image (2).png", import.meta.url).href,
    miniImage: new URL ("../../public/miniProducts/Image (3).png", import.meta.url).href,
  },
  {
    id:2,
    image: new URL("../../public/products/car.png", import.meta.url).href,
    location: "г. Самарканд",
    descraption: "Chevrolet Onix 1.2 Turbo в наличии",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "204 000 000",
    miniImage: new URL ("../../public/miniProducts/Image (1).png", import.meta.url).href,
    miniImage2: new URL ("../../public/miniProducts/Image (2).png", import.meta.url).href,
    miniImage: new URL ("../../public/miniProducts/Image (3).png", import.meta.url).href,
  },
  {
    id:3,
    image: new URL("../../public/products/single_cap.png", import.meta.url).href,
    location: "г. Ташкент",
    descraption: "7Saber Trucker Cap",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "280 000",
    miniImage: new URL ("../../public/miniProducts/Image (1).png", import.meta.url).href,
    miniImage2: new URL ("../../public/miniProducts/Image (2).png", import.meta.url).href,
    miniImage: new URL ("../../public/miniProducts/Image (3).png", import.meta.url).href,
  },
  {
    id:4,
    image: new URL("../../public/products/sneakers.png", import.meta.url).href,
    location: "г. Ташкент",
    descraption: "Оригинальные кроссовки Nike Air Max Plus",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "4 820 000",
    miniImage: new URL ("../../public/miniProducts/Image (1).png", import.meta.url).href,
    miniImage2: new URL ("../../public/miniProducts/Image (2).png", import.meta.url).href,
    miniImage: new URL ("../../public/miniProducts/Image (3).png", import.meta.url).href,
  },
  {
    id:5,
    image: new URL("../../public/products/sneakers2.png", import.meta.url).href,
    location: "г. Ташкент",
    descraption: "Оригинальные кроссовки Nike Air Max 97",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "4 820 000",
    miniImage: new URL ("../../public/miniProducts/Image (1).png", import.meta.url).href,
    miniImage2: new URL ("../../public/miniProducts/Image (2).png", import.meta.url).href,
    miniImage: new URL ("../../public/miniProducts/Image (3).png", import.meta.url).href,
  },
  {
    id:6,
    image: new URL("../../public/products/watches.png", import.meta.url).href,
    location: "г. Ташкент",
    descraption: "Apple Watch Series 8 - USA Non active",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "4 500 000",
    miniImage: new URL ("../../public/miniProducts/Image (1).png", import.meta.url).href,
    miniImage2: new URL ("../../public/miniProducts/Image (2).png", import.meta.url).href,
    miniImage: new URL ("../../public/miniProducts/Image (3).png", import.meta.url).href,
  },
  {
    id:7,
    image: new URL("../../public/products/car2.png", import.meta.url).href,
    location: "г. Самарканд",
    descraption: "Лучший кроссовер Geely Monjaro Limited Edition",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "320 000 000",
    miniImage: new URL ("../../public/miniProducts/Image (1).png", import.meta.url).href,
    miniImage2: new URL ("../../public/miniProducts/Image (2).png", import.meta.url).href,
    miniImage: new URL ("../../public/miniProducts/Image (3).png", import.meta.url).href,
  },
  {
    id:8,
    image: new URL("../../public/products/makeUp.png", import.meta.url).href,
    location: "г. Ташкент",
    descraption: "Стайлер для волос Dyson airwrap complete long",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "6 430 625",
    miniImage: new URL ("../../public/miniProducts/Image (1).png", import.meta.url).href,
    miniImage2: new URL ("../../public/miniProducts/Image (2).png", import.meta.url).href,
    miniImage3: new URL ("../../public/miniProducts/Image (3).png", import.meta.url).href,
    miniImage4:new URL ("../../public/miniProducts/Image (4).png", import.meta.url).href
  },
  {
    id:9,
    image: new URL("../../public/products/cap.png", import.meta.url).href,
    location: "г. Ташкент",
    descraption: "7Saber Trucker Cap",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "280 000",
    miniImage: new URL ("../../public/miniProducts/Image (1).png", import.meta.url).href,
    miniImage2: new URL ("../../public/miniProducts/Image (2).png", import.meta.url).href,
    miniImage: new URL ("../../public/miniProducts/Image (3).png", import.meta.url).href,
  },
  {
    id:10,
    image: new URL("../../public/products/car.png", import.meta.url).href,
    location: "г. Самарканд",
    descraption: "Chevrolet Onix 1.2 Turbo в наличии",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "204 000 000",
    miniImage: new URL ("../../public/miniProducts/Image (1).png", import.meta.url).href,
    miniImage2: new URL ("../../public/miniProducts/Image (2).png", import.meta.url).href,
    miniImage: new URL ("../../public/miniProducts/Image (3).png", import.meta.url).href,
  },
  {
    id:11,
    image: new URL("../../public/products/sneakers.png", import.meta.url).href,
    location: "г. Ташкент",
    descraption: "Оригинальные кроссовки Nike Air Max Plus",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "4 820 000",
    miniImage: new URL ("../../public/miniProducts/Image (1).png", import.meta.url).href,
    miniImage2: new URL ("../../public/miniProducts/Image (2).png", import.meta.url).href,
    miniImage: new URL ("../../public/miniProducts/Image (3).png", import.meta.url).href,
  },
  {
    id:12,
    image: new URL("../../public/products/single_cap.png", import.meta.url)
      .href,
    location: "г. Ташкент",
    descraption: "7Saber Trucker Cap",
    date: "Вчера, 19:20",
    phoneNumber: "+998 71 200 70 07",
    cost: "280 000",
    miniImage: new URL ("../../public/miniProducts/Image (1).png", import.meta.url).href,
    miniImage2: new URL ("../../public/miniProducts/Image (2).png", import.meta.url).href,
    miniImage: new URL ("../../public/miniProducts/Image (3).png", import.meta.url).href,
  },
];

export const category = [
  {
    title: "Для женщин",
    dates: [],
    icon: "icon-girl",
    product_count: "4 147 объявлений",
  },
  {
    title: "Для мужчин",
    dates: [],
    icon: "icon-man",
    product_count: "4 147 объявлений",
  },
  {
    title: "Детские товары",
    dates: [],
    icon: "icon-walk",
    product_count: "4 147 объявлений",
  },
  {
    title: "Здоровье",
    dates: [],
    icon: "icon-heath",
    product_count: "4 147 объявлений",
  },
  {
    title: "Автотовары",
    dates: [],
    icon: "icon-fixed",
    product_count: "4 147 объявлений",
  },
  {
    title: "Электроника",
    dates: [],
    icon: "icon-gadget",
    product_count: "4 147 объявлений",
  },
  {
    title: "Канцелярия",
    dates: [],
    icon: "icon-pen",
    product_count: "4 147 объявлений",
  },
  {
    title: "Строительство и ремонт",
    dates: [],
    icon: "icon-builder",
    product_count: "4 147 объявлений",
  },
  {
    title: "Сумки и чемоданы",
    dates: [],
    icon: "icon-bag",
    product_count: "4 147 объявлений",
  },
  {
    title: "Дача, сады и огороды",
    dates: [],
    icon: "icon-plant",
    product_count: "4 147 объявлений",
  },
  {
    title: "Аксессуарлар",
    dates: [],
    icon: "icon-assessor",
    product_count: "4 147 объявлений",
  },
  {
    title: "Для женщин",
    dates: [],
    icon: "icon-girl",
    product_count: "4 147 объявлений",
  },
  {
    title: "Канцелярия",
    dates: [],
    icon: "icon-pen",
    product_count: "4 147 объявлений",
  },
  {
    title: "Электроника",
    dates: [],
    icon: "icon-gadget",
    product_count: "4 147 объявлений",
  },
  {
    title: "Электроника",
    dates: [],
    icon: "icon-gadget",
    product_count: "4 147 объявлений",
  },
  {
    title: "Электроника",
    dates: [],
    icon: "icon-gadget",
    product_count: "4 147 объявлений",
  },
  {
    title: "Аксессуарлар",
    dates: [],
    icon: "icon-assessor",
    product_count: "4 147 объявлений",
  },
  {
    title: "Сумки и чемоданы",
    dates: [],
    icon: "icon-bag",
    product_count: "4 147 объявлений",
  },
];

export const firstModal = [
  {
    title: "Добро пожаловать!",
    text: "Войти в систему чтобы торговать в системе",
    loginLable: "Логин",
    passLable: "Пароль",
    parol: "Забыли пароль?",
    login: "Войти",
    want: "Хотите стать продавцом?",
    sumbit: "Подать заявку",
  },
];
export const lang = [
    { name: 'Russkiy', flag: '../../public/language/ruLanguage.png' },
    { name: 'O\'zbek', flag: '../../public/language/uzbLanguage.png' },
];
export const filter = [
  { title: "Samarkand" },
  { title: "Khorezm" },
  { title: "Namangan" },
  { title: "Fergana" },
  { title: "Andijan" },
  { title: "Tashkent" },
  { title: "Ko'kan" },
  { title: "Bukhara" },
  { title: "Margilon" }
];
export const forRadio =[
  {title: "Мужчины" },
  {title: "Женщины" },
  {title: "Deti" }
];
export const select = [
  {
    for:"men",
    title: "Мужчины",
    variant: "futbolka",
    variant2: "jemfer", 
    variant3: "oyoq kiyim",
    variant4: "sumka",
    variant5: "Sovg'alar",
    variant6: "gajetlar"
  },
  {
    for:"women",
    title: "Женщины",
    variant: "aksessuarlar",
    variant2: "jemfer",
    variant3: "oyoq kiyim",
    variant4: "sumka",
    variant5: "Sovg'alar",
    variant6: "suinerlar"
  },
  {
    for:"children",
    title: "Дети",
    variant: "futbolka",
    variant2: "jemfer",
    variant3: "oyoq kiyim",
    variant4: "Sovg'alar",
  }

]